# Generated by Django 5.2.8 on 2025-11-27 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_birth_date_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_hash',
        ),
    ]
