# Generated by Django 5.2.8 on 2025-12-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', max_length=5)),
                ('language', models.CharField(choices=[('pt', 'Português'), ('en', 'Inglês')], default='pt', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='day_expired',
        ),
        migrations.RemoveField(
            model_name='task',
            name='language',
        ),
        migrations.RemoveField(
            model_name='task',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='task',
            name='visible_button',
        ),
    ]
