# Generated by Django 5.2.8 on 2025-12-04 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress_points',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
