# Generated by Django 5.2.8 on 2025-12-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_progress_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='day_expired',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
