# Generated by Django 5.2.8 on 2025-12-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_day_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='visible_button',
            field=models.BooleanField(default=True),
        ),
    ]
